In [6]:
import duckdb

In [7]:
import pandas as pd

In [8]:
import os

In [9]:
print(os.getcwd())

c:\Users\lex_a\OneDrive\Desktop\PROJETOS IA\PÓS PROJETO\PROJ1POS\myproject\scripts

In [10]:
from datetime import datetime

In [11]:
con = duckdb.connect(database='dados_duckdb.db',read_only=False)

In [32]:
arquivo = 'z0019_2.csv'
data_injestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_injestao'] = data_injestao
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_injestao
0  10001  PARAFUSO  BT10    100    100  z0019_2.csv 2026-10-10 18:33:25.037856
1  10002   MARTELO  BT50    100   1500  z0019_2.csv 2026-10-10 18:33:25.037856
2  10003     PREGO  BT10    100     50  z0019_2.csv 2026-10-10 18:33:25.037856

In [ ]:
print

2026-10-10 18:23:40.908767

In [33]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_injestao TIMESTAMP
    )     
""")

In [35]:
con.execute("INSERT INTO bronze_produtos SELECT *FROM df")

In [38]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_injestao
0  10001     SERRA  BT50   100   200  z0019_1.csv 2026-10-10 18:25:53.841332
1  10002   MACHADO  BT50   100   100  z0019_1.csv 2026-10-10 18:25:53.841332
2  10003     PREGO  BT10   100    60  z0019_1.csv 2026-10-10 18:25:53.841332
3  10001  PARAFUSO  BT10   100   100  z0019_2.csv 2026-10-10 18:33:25.037856
4  10002   MARTELO  BT50   100  1500  z0019_2.csv 2026-10-10 18:33:25.037856

In [37]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [39]:
con.close()